/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mineT.glb --transform -d 
Files: mineT.glb [3.99MB] > C:\Users\Aryan Gupta\Downloads\Minecraft Portfolio\mineT-transformed.glb [847.23KB] (79%)
*/

import { React, useEffect, useRef, useState, useMemo} from 'react'
import { useGLTF } from '@react-three/drei'
import { useGLTFWithKTX2 } from '../utils/useGLTFWithKTX2';
import { fixMinecraftMaterials } from '../utils/fixMinecraftMaterials';
import * as THREE from "three";
import { useModalStore } from '../stores/modalStore';
import About from '../../components/About/About';
import Connect from '../../components/Connect/Connect';
import Certifications from '../../components/Certifications/Certifications';
import Experiences from '../../components/Experiences/Experiences';
import Skills from '../../components/Skills/Skills';
import Projects from '../../components/Projects/Projects';
import Achievements from '../../components/Achievements/Achievements';

export default function Model({progress = 0, pulseIntensity = 0, ...props}) {
  const { nodes, materials } = useGLTFWithKTX2('/mineT-v1.glb');
  const [hoveredMesh, setHoveredMesh] = useState(null);

  const { openModal } = useModalStore();

  const handleClick = (elementID) => {
    if(elementID === "face"){
      openModal("About me", <About/>, elementID);
    }
    else if(elementID === "connect"){
      openModal("Connect Me", <Connect/>, elementID);
    }
    else if(elementID === "exp"){
      openModal("Experiences", <Experiences/>, elementID);
    }
    else if(elementID === "projects"){
      openModal("Projects", <Projects/>, elementID);
    }
    else if(elementID === "skills"){
      openModal("Skills", <Skills/>, elementID);
    }
    else if(elementID === "achieve"){
      openModal("Achievements", <Achievements/>, elementID);
    }
    else if(elementID === "achieve2"){
      openModal("Certfications", <Certifications/>, elementID);
    }
  }

  const getMaterial = (elementID, progressRange, originalMaterial) => {
    const mat = originalMaterial;

    if (!mat.emissive) {
      mat.emissive = new THREE.Color(0x000000);
    }

    const [min, max] = progressRange;

    const isHovering = hoveredMesh !== null;

    let intensity = 0.05;

    // 🌑 STEP 1: dim everything FIRST if something is hovered
    if (isHovering) {
      intensity = 0.2 + pulseIntensity * 0.2;
    }

    // 🌟 STEP 2: override hovered element
    if (hoveredMesh === elementID) {
      intensity = 0.9;
    }

    // 🌊 STEP 3: pulse overrides only if NOT hovered
    else if (!isHovering && progress >= min && progress <= max) {
      intensity = 0.3 + pulseIntensity * 0.5;
    }

    // ✨ keep subtle base glow
    mat.emissive.setRGB(0.1, 0.1, 0.1);
    mat.emissiveIntensity = intensity;

    return mat;
  };

  useEffect(() => {
    fixMinecraftMaterials(materials);
}, [materials]);

  return (
    <group {...props} dispose={null}>
      <group position={[286.5, 127.5, 152.5]}>
        <mesh geometry={nodes['minecraft_entity-signs-birch001'].geometry} material={materials['minecraft_entity-signs-birch.001']} position={[-281.642, -128.149, -146.856]} rotation={[1.576, 0.001, 1.574]} />
      </group>
      <group position={[286.5, 127.5, 152.5]}>
        <mesh geometry={nodes['minecraft_entity-signs-birch002'].geometry} material={materials['minecraft_entity-signs-birch.002']} position={[-281.642, -128.149, -146.856]} rotation={[1.576, 0.001, 1.574]} />
      </group>
      <group position={[286.5, 127.5, 152.5]}>
        <mesh geometry={nodes['minecraft_entity-signs-oak001'].geometry} material={materials['minecraft_entity-signs-oak.001']} position={[-285.408, -125.982, -144.651]} rotation={[1.576, 0.001, 1.574]} />
      </group>
      <mesh geometry={nodes.clouds.geometry} material={materials.Could} position={[14.743, 74.481, -12.876]} rotation={[2.968, -1.568, 2.962]} scale={189.008} />
      <mesh geometry={nodes.Text.geometry} material={materials['Material.001']} position={[-7.019, 3.324, 5.891]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.113} />
      <mesh geometry={nodes.Text001.geometry} material={materials.Material} position={[-0.63, 3.41, 10.027]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.11} />
      <mesh geometry={nodes.Text002.geometry} material={materials['Material.002']} position={[4.756, -0.651, 4.324]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.102} />
      <mesh geometry={nodes.Text003.geometry} material={materials['Material.003']} position={[4.736, -0.651, 6.474]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.102} />
      <mesh geometry={nodes.Text004.geometry} material={materials['Material.004']} position={[4.736, -0.651, 5.394]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.102} />
      <mesh geometry={nodes.Text005.geometry} material={materials['Material.005']} position={[5.991, -0.67, 6.959]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.097} />
      <mesh geometry={nodes.Text006.geometry} material={materials['Material.006']} position={[5.991, -0.67, 6.029]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.097} />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={getMaterial("face", [0, 1], materials.face)}
        position={[-7.142, 2.349, 5.66]}
        scale={[0.081, 0.532, 0.532]}
        onPointerOver={() => setHoveredMesh("face")}
        onPointerOut={() => setHoveredMesh(null)}
        onClick={()=>{handleClick("face")}}
      />

      <mesh
        geometry={nodes.Cube006.geometry}
        material={getMaterial("connect", [0, 1], materials.connect)}
        position={[-0.618, 2.321, 10.134]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.36, -0.36, -0.03]}
        onPointerOver={() => setHoveredMesh("connect")}
        onPointerOut={() => setHoveredMesh(null)}
        onClick={()=>{handleClick("connect")}}
      />

      <mesh
        geometry={nodes.Cube002.geometry}
        material={getMaterial("exp", [0, 1], materials.exp)}
        position={[4.873, -1.647, 4.636]}
        scale={[0.026, 0.424, 0.424]}
        onPointerOver={() => setHoveredMesh("exp")}
        onPointerOut={() => setHoveredMesh(null)}
        onClick={()=>{handleClick("exp")}}
      />

      <mesh
        geometry={nodes.Cube003.geometry}
        material={getMaterial("projects", [0, 1], materials.projects)}
        position={[4.873, -1.647, 5.636]}
        scale={[0.026, 0.425, 0.425]}
        onPointerOver={() => setHoveredMesh("projects")}
        onPointerOut={() => setHoveredMesh(null)}
        onClick={()=>{handleClick("projects")}}
      />

      <mesh
        geometry={nodes.Cube004.geometry}
        material={getMaterial("skills", [0, 1], materials.skills)}
        position={[4.873, -1.647, 6.636]}
        scale={[0.026, 0.426, 0.426]}
        onPointerOver={() => setHoveredMesh("skills")}
        onPointerOut={() => setHoveredMesh(null)}
        onClick={()=>{handleClick("skills")}}
      />

      <mesh
        geometry={nodes.Cube.geometry}
        material={getMaterial("achieve", [0, 1], materials.achieve)}
        position={[5.977, -1.655, 6.651]}
        scale={[0.035, 0.395, 0.395]}
        onPointerOver={() => setHoveredMesh("achieve")}
        onPointerOut={() => setHoveredMesh(null)}
        onClick={()=>{handleClick("achieve")}}
      />

      <mesh
        geometry={nodes.Cube001.geometry}
        material={getMaterial("achieve2", [0, 1], materials['achieve.001'])}
        position={[5.967, -1.655, 5.631]}
        scale={[0.035, 0.395, 0.395]}
        onPointerOver={() => setHoveredMesh("achieve2")}
        onPointerOut={() => setHoveredMesh(null)}
        onClick={()=>{handleClick("achieve2")}}
      />
      <mesh geometry={nodes.Text007.geometry} material={materials['Material.015']} position={[-9.121, 2.944, 7.493]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.259} />
      <mesh geometry={nodes['minecraft_block-allium'].geometry} material={materials['minecraft_block-allium']} position={[-14.609, 0.452, 8.092]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-andesite'].geometry} material={materials['minecraft_block-andesite']} position={[-6.021, -9.045, -2.416]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-azalea_leaves'].geometry} material={materials['minecraft_block-azalea_leaves']} position={[6.393, 2.843, 7.168]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-beehive_end'].geometry} material={materials['minecraft_block-beehive_end']} position={[13.396, -3.153, 7.155]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-beehive_front'].geometry} material={materials['minecraft_block-beehive_front']} position={[12.896, -2.653, 7.156]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-beehive_side'].geometry} material={materials['minecraft_block-beehive_side']} position={[13.896, -2.653, 7.159]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-black_stained_glass'].geometry} material={materials['minecraft_block-black_stained_glass']} position={[-0.035, 3.055, 7.007]} rotation={[1.576, 0.001, 1.574]} renderOrder={10} />
      <mesh geometry={nodes['minecraft_block-black_wool'].geometry} material={materials['minecraft_block-black_wool']} position={[-12.611, 3.859, 8.117]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-blue_orchid'].geometry} material={materials['minecraft_block-blue_orchid']} position={[-5.606, 0.794, 7.287]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-bookshelf'].geometry} material={materials['minecraft_block-bookshelf']} position={[13.395, -0.903, 7.168]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-brown_wool'].geometry} material={materials['minecraft_block-brown_wool']} position={[0.114, -0.913, 8.35]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-candle_lit'].geometry} material={materials['minecraft_block-candle_lit']} position={[1.366, 2.066, 9.629]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-cobblestone'].geometry} material={materials['minecraft_block-cobblestone']} position={[-13.108, -0.173, 8.092]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-composter_bottom'].geometry} material={materials['minecraft_block-composter_bottom']} position={[6.394, 0.968, 7.157]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-composter_ready'].geometry} material={materials['minecraft_block-composter_ready']} position={[6.393, 1.781, 7.162]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-composter_side'].geometry} material={materials['minecraft_block-composter_side']} position={[6.394, 1.343, 7.16]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-composter_top'].geometry} material={materials['minecraft_block-composter_top']} position={[6.393, 1.843, 7.162]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-crafting_table_top'].geometry} material={materials['minecraft_block-crafting_table_top']} position={[-0.613, 0.825, 9.636]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-crimson_roots_pot'].geometry} material={materials['minecraft_block-crimson_roots_pot']} position={[6.398, 2.477, 5.666]} rotation={[1.576, 0.001, 1.574]} />
      {/* <mesh geometry={nodes['minecraft_block-dark_oak_door_bottom'].geometry} material={materials['minecraft_block-dark_oak_door_bottom']} position={[-2.928, -0.268, 8.322]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-dark_oak_door_top'].geometry} material={materials['minecraft_block-dark_oak_door_top']} position={[-2.929, 0.732, 8.328]} rotation={[1.576, 0.001, 1.574]} /> */}
      <mesh geometry={nodes['minecraft_block-dark_oak_planks'].geometry} material={materials['minecraft_block-dark_oak_planks']} position={[-4.739, 2.375, 9.632]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-dark_oak_trapdoor'].geometry} material={materials['minecraft_block-dark_oak_trapdoor']} position={[5.39, 2.337, 8.162]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-dirt'].geometry} material={materials['minecraft_block-dirt']} position={[5.909, 0.721, 21.283]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-end_rod'].geometry} material={materials['minecraft_block-end_rod']} position={[10.395, -1.873, 7.154]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-flower_pot'].geometry} material={materials['minecraft_block-flower_pot']} position={[0.943, 1.177, 7.292]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-flowering_azalea_leaves'].geometry} material={materials['minecraft_block-flowering_azalea_leaves']} position={[6.393, 2.843, 7.168]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-furnace_top'].geometry} material={materials['minecraft_block-furnace_top']} position={[4.401, -3.649, 5.625]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-glass'].geometry} material={materials['minecraft_block-glass']} position={[8.485, 0.539, 7.122]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-glass_pane_top'].geometry} material={materials['minecraft_block-glass_pane_top']} position={[9.54, 1.345, 7.092]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-grass_block_side'].geometry} material={materials['minecraft_block-grass_block_side']} position={[2.563, 4.93, 28.556]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-grass_block_top'].geometry} material={materials['minecraft_block-grass_block_top']} position={[1.95, 4.97, 30.072]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-gravel'].geometry} material={materials['minecraft_block-gravel']} position={[16.145, -10.54, 2.658]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-gray_wool'].geometry} material={materials['minecraft_block-gray_wool']} position={[-4.685, 0.877, 5.707]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-iron_trapdoor'].geometry} material={materials['minecraft_block-iron_trapdoor']} position={[-1.108, 4.933, 7.157]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-item_frame'].geometry} material={materials['minecraft_block-item_frame']} position={[6.97, 0.715, 6.933]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-jukebox_side'].geometry} material={materials['minecraft_block-jukebox_side']} position={[6.4, -2.648, 5.637]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-jukebox_top'].geometry} material={materials['minecraft_block-jukebox_top']} position={[6.4, -2.148, 5.64]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-kelp'].geometry} material={materials['minecraft_block-kelp']} position={[11.291, -3.003, -31.995]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-kelp_plant'].geometry} material={materials['minecraft_block-kelp_plant']} position={[6.912, -6.346, -29.754]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-lantern'].geometry} material={materials['minecraft_block-lantern']} position={[0.642, 1.825, 7.645]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-large_fern_bottom'].geometry} material={materials['minecraft_block-large_fern_bottom']} position={[19.878, 7.428, 50.441]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-large_fern_top'].geometry} material={materials['minecraft_block-large_fern_top']} position={[19.878, 8.428, 50.447]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-light_gray_wool'].geometry} material={materials['minecraft_block-light_gray_wool']} position={[8.832, -3.176, 7.28]} rotation={[1.576, 0.001, 1.574]} />
      <mesh visible={false} geometry={nodes['minecraft_block-medium_amethyst_bud'].geometry} material={materials['minecraft_block-medium_amethyst_bud']} position={[2.386, 2.327, 9.653]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-oak_leaves'].geometry} material={materials['minecraft_block-oak_leaves']} position={[-32.334, 16.029, -39.578]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-oak_log'].geometry} material={materials['minecraft_block-oak_log']} position={[-31.424, 14.726, -40.075]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-oak_log_top'].geometry} material={materials['minecraft_block-oak_log_top']} position={[-31.407, 17.279, -40.878]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-oak_planks'].geometry} material={materials['minecraft_block-oak_planks']} position={[-3.783, 0.626, 7.431]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-oak_trapdoor'].geometry} material={materials['minecraft_block-oak_trapdoor']} position={[2.394, 1.748, 7.15]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-polished_andesite'].geometry} material={materials['minecraft_block-polished_andesite']} position={[10.394, 1.345, 7.172]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-polished_blackstone'].geometry} material={materials['minecraft_block-polished_blackstone']} position={[9.255, 1.332, 7.002]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-poppy'].geometry} material={materials['minecraft_block-poppy']} position={[6.639, 0.699, 46.906]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-potted_azalea_bush_plant'].geometry} material={materials['minecraft_block-potted_azalea_bush_plant']} position={[1.893, 2.466, 7.152]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-potted_azalea_bush_side'].geometry} material={materials['minecraft_block-potted_azalea_bush_side']} position={[1.893, 2.591, 7.153]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-potted_azalea_bush_top'].geometry} material={materials['minecraft_block-potted_azalea_bush_top']} position={[1.893, 2.838, 7.155]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-potted_flowering_azalea_bush_plant'].geometry} material={materials['minecraft_block-potted_flowering_azalea_bush_plant']} position={[2.726, 2.466, 7.155]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-potted_flowering_azalea_bush_side'].geometry} material={materials['minecraft_block-potted_flowering_azalea_bush_side']} position={[2.726, 2.591, 7.156]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-potted_flowering_azalea_bush_top'].geometry} material={materials['minecraft_block-potted_flowering_azalea_bush_top']} position={[2.726, 2.838, 7.157]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-quartz_block_bottom'].geometry} material={materials['minecraft_block-quartz_block_bottom']} position={[2.884, 0.142, 7.061]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-quartz_block_side'].geometry} material={materials['minecraft_block-quartz_block_side']} position={[1.925, -2.017, 7.551]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-quartz_block_top'].geometry} material={materials['minecraft_block-quartz_block_top']} position={[0.768, -1.915, 8.124]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-red_sandstone_top'].geometry} material={materials['minecraft_block-red_sandstone_top']} position={[-5.341, 1.41, 5.505]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-red_tulip'].geometry} material={materials['minecraft_block-red_tulip']} position={[12.395, -1.529, 7.161]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-sand'].geometry} material={materials['minecraft_block-sand']} position={[1.204, -0.731, -6.993]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-sandstone'].geometry} material={materials['minecraft_block-sandstone']} position={[-13.149, 0.368, -15.023]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-sandstone_bottom'].geometry} material={materials['minecraft_block-sandstone_bottom']} position={[-10.714, -0.045, -8.712]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-sandstone_top'].geometry} material={materials['minecraft_block-sandstone_top']} position={[-18.252, 1.728, -22.967]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-sea_lantern'].geometry} material={materials['minecraft_block-sea_lantern']} position={[8.848, -7.309, 6.339]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-seagrass'].geometry} material={materials['minecraft_block-seagrass']} position={[6.567, -10.348, -9.591]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-spruce_leaves'].geometry} material={materials['minecraft_block-spruce_leaves']} position={[0.775, 7.431, 43.444]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-spruce_log'].geometry} material={materials['minecraft_block-spruce_log']} position={[3.627, 5.57, 45.473]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-spruce_log_top'].geometry} material={materials['minecraft_block-spruce_log_top']} position={[4.637, 8.82, 45.201]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-spruce_planks'].geometry} material={materials['minecraft_block-spruce_planks']} position={[7.597, -0.377, 6.454]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-spruce_trapdoor'].geometry} material={materials['minecraft_block-spruce_trapdoor']} position={[3.525, 0.641, 7.503]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-stone'].geometry} material={materials['minecraft_block-stone']} position={[3.2, -9.202, -0.976]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-stone_bricks'].geometry} material={materials['minecraft_block-stone_bricks']} position={[-12.609, 0.328, 8.097]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-stripped_cherry_log'].geometry} material={materials['minecraft_block-stripped_cherry_log']} position={[11.398, -2.649, 6.319]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-sugar_cane'].geometry} material={materials['minecraft_block-sugar_cane']} position={[65.26, 1.122, 51.836]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-tall_seagrass_bottom'].geometry} material={materials['minecraft_block-tall_seagrass_bottom']} position={[7.153, -10, -8.8]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-tall_seagrass_top'].geometry} material={materials['minecraft_block-tall_seagrass_top']} position={[3.604, -8.633, -8.033]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-torchflower'].geometry} material={materials['minecraft_block-torchflower']} position={[3.386, 2.452, 9.657]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-warped_roots_pot'].geometry} material={materials['minecraft_block-warped_roots_pot']} position={[6.395, 2.471, 6.666]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_block-water_still'].geometry} material={materials['minecraft_block-water_still']} position={[5.36, -6.986, 3.229]} rotation={[1.576, 0.001, 1.574]} renderOrder={5}/>
      <mesh geometry={nodes['minecraft_entity-armorstand-wood'].geometry} material={materials['minecraft_entity-armorstand-wood']} position={[8.388, -2.33, 9.645]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_entity-bed-red'].geometry} material={materials['minecraft_entity-bed-red']} position={[11.896, -2.994, 7.152]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_entity-chest-normal'].geometry} material={materials['minecraft_entity-chest-normal']} position={[6.554, -2.622, 6.637]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_entity-signs-birch'].geometry} material={materials['minecraft_entity-signs-birch']} position={[4.858, -0.649, 5.644]} rotation={[1.576, 0.001, 1.574]} />
      <mesh geometry={nodes['minecraft_entity-signs-oak'].geometry} material={materials['minecraft_entity-signs-oak']} position={[1.092, 1.518, 7.849]} rotation={[1.576, 0.001, 1.574]} />
    </group>
  )
}